name: RMV

services:
  - name: app
    type: nodejs
    env:
      MYSQL_HOST: mysql.railway.internal
      MYSQL_USER: root
      MYSQL_PASSWORD: JEWZIacsisWhxsrEdTrHKjGwEMjvPxKO
      MYSQL_DATABASE: railway
      MYSQL_PORT: 3306
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: refrielectricmv@gmail.com
      SMTP_PASS: rlfp pitl xfuu odnu
      PAYPAL_CLIENT_ID: AX2kwfBLc6X6tevJto9iZ6-yUVrt5GjvXHe2cEQZzJg7aSQrFlGjOZy-SgZKgh4PAOGiPnQtG76XhwT9
      PORT: 3000
      NODE_ENV: production
      VITE_API_URL: https://rmv-production.up.railway.app
      RAILWAY_PRIVATE_DOMAIN: containers-us-west-123.railway.app
    build:
      image: node:18
      command: |
        cp railway.env .env
        # Copiar código fuente del backend
        cp -r ../Backend/* .
        # Copiar package.json del backend
        cp ../package*.json .
        # Instalar dependencias del backend
        npm install --legacy-peer-deps
        # Instalar dependencias del frontend
        cd frontend
        npm install --legacy-peer-deps
        # Instalar Vite globalmente
        npm install -g vite
        # Copiar código fuente del frontend
        cp -r ../frontend/* .
        # Construir el frontend
        npm run build
        cd ..
    deploy:
      command: |
        cp railway.env .env
        # Construir el frontend
        cd frontend
        npm run build
        cd ..
        # Iniciar el servidor
        cd Backend && npm start
    ports:
      - 3000:3000
      - 5173:5173
    volumes:
      - ./frontend/dist:/app/frontend/dist
      - ./Backend:/app/Backend
      - ./railway.env:/app/.env
    volumes:
      - ./frontend/dist:/app/frontend/dist
      - ./Backend:/app/Backend

  - name: mysql
    type: mysql
    env:
      MYSQL_ROOT_PASSWORD: JEWZIacsisWhxsrEdTrHKjGwEMjvPxKO
      MYSQL_DATABASE: railway
      MYSQL_USER: root
      MYSQL_PASSWORD: JEWZIacsisWhxsrEdTrHKjGwEMjvPxKO
      MYSQL_PORT: 3306
      RAILWAY_PRIVATE_DOMAIN: mysql.railway.internal
    ports:
      - 3306:3306
